### ISSUE TITLE
python version installation failure

### ISSUE THREAD

**Issue by ghost** [ruveydayilmaz0/BVDM#1]
Hi author! I used python3.8 but fount it is not fitting a lot of packages in the requirements.txt, what python version should I use to fit the requirements?

**Comment by ruveydayilmaz0** [comment]
Hi Istan, Python version 3.8.19 should work for the packages. Let me know if you have any problems.

**Comment by ghost** [comment]
> Hi Istan, Python version 3.8.19 should work for the packages. Let me know if you have any problems.

Thanks a lot for your help!
